{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{%   for key, val in item.env.items() %}
{%     if val %}
ENV {{ key }}="{{ val }}"
{%     endif %}
{%   endfor %}
{% endif %}

RUN mkdir -p /var/run/sshd

RUN useradd -d /home/${USERNAME} -m -s /bin/bash ${USERNAME}
RUN echo "${USERNAME}:${PASSWORD}" | chpasswd
RUN echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN mkdir -p /home/${USERNAME}/.ssh
RUN chown -R ${USERNAME} /home/${USERNAME}/.ssh
RUN chmod 0700 /home/${USERNAME}/.ssh
RUN touch /home/${USERNAME}/.ssh/authorized_keys
RUN chown ${USERNAME} /home/${USERNAME}/.ssh/authorized_keys
RUN chmod 0600 /home/${USERNAME}/.ssh/authorized_keys
RUN echo "${PUBKEY}" >> /home/${USERNAME}/.ssh/authorized_keys
