FROM stackstorm/packagingtest:centos7-systemd

RUN set -eu \
  && useradd --create-home --user-group {{ item.username }} \
  && echo "{{ item.username }}:{{ item.password }}"| chpasswd {{ item.username }} \
  && usermod --append --groups wheel {{ item.username }} \
  && echo "{{ item.username }} ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/{{ item.username }} \
  && mkdir -p /home/{{ item.username }}/.ssh \
  && chown -R {{ item.username }} /home/{{ item.username }}/.ssh \
  && chmod 0700 /home/{{ item.username }}/.ssh \
  && touch /home/{{ item.username }}/.ssh/authorized_keys \
  && chown {{ item.username }} /home/{{ item.username }}/.ssh/authorized_keys \
  && chmod 0600 /home/{{ item.username }}/.ssh/authorized_keys \
  && echo "{{ item.pubkey }}" >> /home/{{ item.username }}/.ssh/authorized_keys
