FROM stackstorm/packagingtest:rockylinux8-systemd

ARG USERNAME=molecule
ARG PASSWORD=molecule
ARG PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdCmmPjsOBWRXc+PKdgDRrsciNjp25zTacyz8Gdkln2ma046brOYXAphhp/85DKgHtANBBt3cl4+HnpDbmAfyq2qZT7hWzAbMxtq0Sj+yyFyUdreXoe4gEKyxpV6o8p/R/XzEcawvqX/vFc5EIFmvTdamxZs9DQmOE5AZMzUB18Kerkrb0/arUcZ8iMi9Ng9a18avow+7oUFZ6Oub7ISz/dkIRojaKO/2paJZ4p+v7ZLn7Hq8TUeBkgAlx872oh8J8linhIq17zK6x4MGL8qiurp2hnfe0cuCxwcsYGy+4DfK51+E2vks6FprCIfF5hIdz26euPn67/YpM0F0b5nXF busybee@drone"

RUN mkdir -p /var/run/sshd

RUN useradd -d /home/${USERNAME} -m -s /bin/bash ${USERNAME}
RUN echo "${USERNAME}:${PASSWORD}" | chpasswd
RUN echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN mkdir -p /home/${USERNAME}/.ssh
RUN chown -R ${USERNAME} /home/${USERNAME}/.ssh
RUN chmod 0700 /home/${USERNAME}/.ssh
RUN touch /home/${USERNAME}/.ssh/authorized_keys
RUN chown ${USERNAME} /home/${USERNAME}/.ssh/authorized_keys
RUN chmod 0600 /home/${USERNAME}/.ssh/authorized_keys
RUN echo "${PUBKEY}" >> /home/${USERNAME}/.ssh/authorized_keys

RUN yum install -y ansible-core
RUN ansible-galaxy collection install community.rabbitmq ansible.posix community.general
