---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  -
    name: ubuntu-18.04
    pre_build_image: true
    image: stackstorm/packagingtest:bionic-systemd
    privileged: true
    command: /sbin/init
    tmpfs: [/run, /tmp]
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:ro]
  -
    name: ubuntu-20.04
    pre_build_image: true
    image: stackstorm/packagingtest:focal-systemd
    privileged: true
    command: /sbin/init
    tmpfs: [/run, /tmp]
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:ro]
  -
    name: centos-7
    pre_build_image: false
    image: stackstorm/packagingtest:centos7-systemd
    privileged: true
    dockerfile: Dockerfile.centos7.j2
    command: /sbin/init
    tmpfs: [/run, /tmp]
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:ro]
    env:
      USERNAME: molecule
      PASSWORD: molecule
      PUBKEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdCmmPjsOBWRXc+PKdgDRrsciNjp25zTacyz8Gdkln2ma046brOYXAphhp/85DKgHtANBBt3cl4+HnpDbmAfyq2qZT7hWzAbMxtq0Sj+yyFyUdreXoe4gEKyxpV6o8p/R/XzEcawvqX/vFc5EIFmvTdamxZs9DQmOE5AZMzUB18Kerkrb0/arUcZ8iMi9Ng9a18avow+7oUFZ6Oub7ISz/dkIRojaKO/2paJZ4p+v7ZLn7Hq8TUeBkgAlx872oh8J8linhIq17zK6x4MGL8qiurp2hnfe0cuCxwcsYGy+4DfK51+E2vks6FprCIfF5hIdz26euPn67/YpM0F0b5nXF busybee@drone"
  -
    name: rockylinux-8
    pre_build_image: false
    image: stackstorm/packagingtest:rockylinux8-systemd
    privileged: true
    dockerfile: Dockerfile.rockylinux8.j2
    command: /sbin/init
    tmpfs: [/run, /tmp]
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:ro]
    env:
      USERNAME: molecule
      PASSWORD: molecule
      PUBKEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdCmmPjsOBWRXc+PKdgDRrsciNjp25zTacyz8Gdkln2ma046brOYXAphhp/85DKgHtANBBt3cl4+HnpDbmAfyq2qZT7hWzAbMxtq0Sj+yyFyUdreXoe4gEKyxpV6o8p/R/XzEcawvqX/vFc5EIFmvTdamxZs9DQmOE5AZMzUB18Kerkrb0/arUcZ8iMi9Ng9a18avow+7oUFZ6Oub7ISz/dkIRojaKO/2paJZ4p+v7ZLn7Hq8TUeBkgAlx872oh8J8linhIq17zK6x4MGL8qiurp2hnfe0cuCxwcsYGy+4DfK51+E2vks6FprCIfF5hIdz26euPn67/YpM0F0b5nXF busybee@drone"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    ST2_REPO: stable
    HUBOT_SLACK_TOKEN: xoxb-hunter2
  inventory:
    vars:
      st2repo_name: stable
      st2chatops_hubot_adapter: slack
      st2chatops_config:
        HUBOT_SLACK_TOKEN: xoxb-hunter2
      st2_rbac_enable: true

verifier:
  name: ansible

# lint: |
#   set -e
#   yamllint .
#   flake8
#   ansible-lint

scenario:
  create_sequence:
    # - dependency
    - create
    # - prepare
  check_sequence:
    # - dependency
    - cleanup
    - destroy
    - create
    # - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency
    - create
    # - prepare
    - converge
  destroy_sequence:
    # - dependency
    - cleanup
    - destroy
  test_sequence:
    # - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
