---
galaxy_info:
  description: Install MongoDB
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions: ["bionic", "focal"]
    - name: EL
      versions: ["7", "8"]
  galaxy_tags:
    - system
  role_name: st2_mongodb
dependencies:
  - role: st2_epel
    when: ansible_facts.os_family == 'RedHat'
