name: lint

on:
  workflow_dispatch:
  push:
    branches:
      # only on merges to master branch
      - master
      - ansible-lint-2
    tags:
      - v*
  pull_request:
    types: [opened, synchronize]

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - "2.10.3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade ansible==${{ matrix.ansible-core }}
          python3 -m pip install --upgrade ansible-lint
          ansible --version
          ansible-lint --version
